[package]
name = "mazegen"
version = "0.1.0"
authors = ["Will Duquette <will@wjduquette.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
molt = "0.3.1"
molt-shell = "0.3.1"
rand = "0.7.3"
image = "0.23.4"
